services:
  - type: web
    name: cookbook
    env: python
    plan: free
    region: frankfurt
    buildCommand: |
      pip install -r Backend/requirements.txt
      cd frontend && npm ci --only=production && npm run build
    startCommand: gunicorn Backend.app:app
    healthCheckPath: /